### ISSUE TITLE
Feature Request: Support Swift PM

### ISSUE THREAD

**Issue by laosb** [GEOSwift/GEOSwiftMapKit#4]
GEOSwift has already supported Swift PM. Please support it so we can use it more easily.

**Comment by macdrevx** [comment]
Hi @laosb, this is definitely something we want to support. There are some challenges to supporting SPM in geos (the library that GEOSwift is built on), but once those are resolved, we can roll out support to GEOSwift and this library too.

GEOSwift currently works with SPM only on macOS and Linux. It does it by linking with a package-manager-provided geos (homebrew and apt). This solution won’t work for iOS and tvOS though, which is why we need to update our geos project to be able to build with SPM.

**Comment by macdrevx** [comment]
https://github.com/GEOSwift/geos/issues/11

**Comment by macdrevx** [comment]
https://github.com/GEOSwift/GEOSwift/issues/166

**Comment by macdrevx** [comment]
@laosb SPM support is now available starting with v 1.2.0

**Comment by laosb** [comment]
@macdrevx Just tried adding GEOSwiftMapKit to my Xcode iOS project via Xcode SwiftPM integration, and it failed when I try to run:

```
dyld: Library not loaded: @rpath/libgeos.dylib
  Referenced from: /private/var/containers/Bundle/Application/[REDACTED]/[REDACTED].app/[REDACTED]
  Reason: image not found
(lldb) 
```

Versions:

![image](https://user-images.githubusercontent.com/2545261/69425936-e0f1f500-0d66-11ea-9351-3af03e5c4d74.png)

Those are figured out by Swift PM itself.

And it works charmingly on simulator, but only leaves such an error on application starting when tested on an actual device.

**Comment by macdrevx** [comment]
Thanks @laosb. Let’s start a new issue to track this problem.
